EaseHee/AcornReact2

package-lock.json, package.json, src/components/ui/alert.jsx, src/components/ui/close-button.jsx, src/components/ui/custom-alert.jsx, src/pages/auth/AuthLogin.jsx, src/pages/auth/AuthRegister.jsx, src/pages/auth/DuplicatedEmail.jsx, src/pages/auth/FindEmail.jsx, src/pages/auth/FindEmailModal.jsx, src/pages/auth/FindPassword.jsx, src/pages/auth/FindPasswordModal.jsx
=> feat : Auth

package-lock.json, package.json, src/App.js, src/components/CustomDialog.jsx, src/components/InfiniteScrollDemo.jsx, src/pages/tab-group/TabGroup.jsx, src/pages/tab-group/Tabs/BlogReviews.jsx, src/pages/tab-group/Tabs/FreeComments.jsx, src/pages/tab-group/Tabs/StarReviews.jsx, src/pages/tab-group/Tabs/dialog-body/CreateReview.jsx
다른 리액트 버전(19.0.0)에서 작업하여 발생한 병합문제 해결.
=> 병합을 위해 import경로 수정 완료

package-lock.json
package-lock.json 파일 내 typescript 관련 의존성 설정 추가 (npm install 시 자동 추가된 설정)
=> chore: add package-lock.json for dependency management

package-lock.json, package.json, public/index.html, src/App.js, src/pages/details/DetailPage.jsx, src/pages/details/Map.jsx, src/pages/main/Main.js, src/pages/main/MainCard.js, src/utils/KakaoMaps.js
화면 새로고침 시 지도가 하얗게 보이는 문제 해결 중
=> feat: 사용자 현재 위치로 부터 도로명 주소 반환 & 상세 페이지 지도에 음식점 주소 설정

src/pages/auth/KakaoLogin.jsx
=> feat: 카카오 간편 로그인 API 요청

src/pages/auth/AuthLogin.jsx, src/pages/main/Main.js
=> feat: 로그인, 로그아웃 개발

src/pages/auth/AuthLogin.jsx
=> feat: 이메일 기억하기 기능 추가

src/pages/auth/AuthLogin.jsx, src/pages/auth/AuthRegister.jsx, src/pages/mypage/DeleteAccount.jsx, src/pages/mypage/DuplicatedNickname.jsx, src/pages/mypage/MyPage.jsx, src/pages/mypage/ProfileForm.jsx
=> feat: 프로필 수정 / 회원탈퇴 개발

src/pages/auth/AuthLogin.jsx, src/pages/mypage/DeleteAccount.jsx, src/pages/mypage/MyPage.jsx, src/pages/mypage/ProfileForm.jsx
fix: 프로필 수정 폼 유효성 문제 해결 및 API 요청 엔드포인트 변경
=> fix: 프로필 수정 폼 유효성 문제 해결 및 API 요청 엔드포인트 변경

src/pages/mypage/Tabs/StarReview/CustomDialog.jsx, src/pages/mypage/Tabs/StarReview/StarReviewCard.js, src/pages/mypage/Tabs/StarReview/StarReviews.jsx
마이페이지 탭 구분 및 회원별 별점리뷰 수정까지 구현했습니다.
=> feat:마페 별리 구현

src/pages/main/MainCard.js
=> fix: merge

src/components/InfiniteScrollDemo.jsx, src/pages/details/Tabs/FreeComments.jsx
=> fix/댓글기능 구현 완료

src/pages/details/DetailPage.jsx, src/pages/mypage/Tabs/Favorites/BookmarkCard.jsx, src/pages/mypage/Tabs/Favorites/MyBookmark.jsx
=> feat: favorite

src/pages/main/Main.js, src/pages/main/MainCard.js, src/pages/main/filter/CategoryDialog.js, src/pages/main/filter/Filter.jsx, src/pages/main/filter/LocationDialog.js, src/redux/slices/filterSlice.js
Wrapper 엘리먼트 속성 추가 : id="scrollableContainer"
<InfiniteScroll 
scrollableTarget="scrollableContainer"
>
props 설정 추가
=> fix: 메인 스크롤 무한 로딩 문제 수정

src/components/swiper/Swiper.js, src/components/swiper/mainswiper.css, src/pages/details/ReviewTabs.jsx, src/pages/details/Tabs/FreeComments.jsx, src/pages/details/Tabs/StarReview/CustomDialog.jsx, src/pages/details/Tabs/StarReview/StarReviews.jsx, src/pages/mypage/MyPage.jsx, src/pages/mypage/MyTabs.jsx, src/pages/mypage/Tabs/StarReview/CustomDialog.jsx, src/pages/mypage/Tabs/StarReview/DeleteDialog.js, src/pages/mypage/Tabs/StarReview/StarReviewCard.js, src/pages/templates/main/Footer.jsx, src/pages/templates/main/Header.jsx
=> feat : 비로그인 접근 방지 및 세부 디자인 수정

src/pages/main/Main.js
필터 선택 여부에 따른 우선 순위에 의해 요청 처리가 되지 않는 문제.
별도의 요청에 의해 추천 알고리즘 데이터를 반환하도록 해야할 듯함
=> fix: 메인 화면 로그인 여부에 따른 구분 요청 미적용

src/pages/auth/AuthLogin.jsx, src/pages/auth/AuthRegister.jsx, src/pages/auth/FindEmail.jsx, src/pages/auth/FindPassword.jsx, src/pages/mypage/Tabs/MyInfo/DeleteAccount.jsx, src/pages/mypage/Tabs/MyInfo/DuplicatedNickname.jsx, src/pages/mypage/Tabs/MyInfo/ProfileForm.jsx, src/pages/templates/main/Footer.jsx, src/pages/templates/main/Header.jsx
=> fix : 회원탈퇴 로직 수정

src/pages/auth/AuthRegister.jsx, src/pages/mypage/Tabs/MyInfo/ProfileForm.jsx
fix : 생년월일 유효성 검증, 프로필 수정 비밀번호 required
=> fix : 생년월일 유효성 검증, 프로필 수정 비밀번호 required

src/pages/auth/DuplicatedEmail.jsx
=> feat : 이메일 패턴 유효성 검증 추가 개발

src/pages/main/Main.js
flex -> grid
마지막 행의 개수가 2개인 경우 가운데에 공백이 생기는 문제 해결
=> fix: 메인화면 목록 출력 방식 변경

src/components/Logo.jsx, src/components/swiper/Swiper.js, src/pages/details/ImageSlider.jsx, src/pages/templates/main/GTranslate.css, src/pages/templates/main/GTranslate.jsx, src/pages/templates/main/Header.jsx
다국어 cdn 기능 추가, 로고 클릭시 새로고침, 메인슬라이더 스크롤 비활성화
=> feat: 다국어 cdn
